mutation($idBudget:ID!, $idUser:ID!){
    AddBudgetWith_user(
        from:{
            id:$idBudget
        },
        to:{
            id:$idUser
        }
    ){
        from{id},
        to{id}
    },
}