query($date_start: String, $date_final: String) {
    Budget(filter:{AND: [{date_gte: {formatted: $date_start}}, {date_lte: {formatted: $date_final}}]}){
     date {
                       formatted
                       },
                       id,
                      discount,
                      value,
                      payments,
                      parcels,
                      payment_methods,
                      user: with_user{
                        id, name, email, cpf,telephones
                      }
                      products: with_productBundget{
                         price,
                         id,
                         with_product{
                         id,
                            name,
                            type,
                          },
                         clinic: with_clinic{
                            id,
                            name
                         }
                       },
                      with_transaction{
                         id
                      },
    }
}