language: node_js
node_js:
  - "4.0"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - npm install
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN
