language: node_js
node_js:
  - "11.0.0"
install:
  - npm install -g firebase-tools
before_script:
  - npm install
script:
  - npm run build
  - ls -la
  - firebase use prosaude-36f66 --token $FIREBASE_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN
#after_script:
#  - ls -la
#  - firebase deploy --token $FIREBASE_TOKEN
