mutation {
    AddProductTransactionWith_clinic(
        from:{
            id:$idProductTransaction
        },
        to:{
            id:$idClinic
        }
    ){
        from{id},
        to{id}
    },
}