mutation {
    AddProductTransactionWith_product(
        from:{
            id:$idTransactionProduct
        },
        to:{
            id:$idProduct
        }
    ){
        from{id},
        to{id}
    },
}