mutation($idConsultation: ID!, $idPatient: ID!, $idSchedule:ID!,$idProduct:ID!, $idClinic: ID!, $idDoctor: ID!){
    AddPatientWith_consultation(
        from:{
            id:$idPatient
        },
        to:{
            id:$idConsultation
        }
    ){
        from{
            id
        },
        to{
            id
        }
    }

    AddConsultationCame_from(
        from:{
            id:$idConsultation
        },
        to:{
            id:$idSchedule
        }
    ){
        from{id},
        to{id}
    },
    AddConsultationHas_product(
        from:{
            id:$idConsultation
        },
        to:{
            id:$idProduct
        }
    ){
        from{id},
        to{id}
    },
    AddConsultationOf_clinic(
        from:{
            id:$idConsultation
        },
        to:{
            id:$idClinic
        }
    ){
        from{id},
        to{id}
    },
    AddConsultationAttended_by(
        from:{
            id:$idConsultation
        },
        to:{
            id:$idDoctor
        }
    ){
        from{id},
        to{id}
    }
}