query($idClinic:ID, $idProduct:ID, $date:_Neo4jDateTimeInput){
  Consultation(orderBy:[date_asc],filter:{has_product:{id:$idProduct}, of_clinic:{id:$idClinic}, date_gte:$date,came_from_not:null}){
    id,
      type,
      status,
      date{formatted},
      payment_number,
      clinic:of_clinic{
        id,name,logo
      },
      product:has_product{
        id,name,type,price
      },
      doctor:attended_by{
        id,name,crm
      },
      regress{
        id,
        type,
        status,
        date{formatted},
        payment_number
      },
      previous_consultation{
        id,
        type,
        status,
        date{formatted},
        payment_number
      },
    	patient{
        id,
        name,
        cpf,
        birth_date{
          formatted
        },
      },
      dependent{
        id,
        name,
        birth_date{formatted},
        dependentDegree,
        sex
      }
      came_from{
        id
      },
      productTransaction{
        id
      }
  }
}
