mutation($idSchedule:ID!, $idConsultation:ID!){
    RemoveConsultationCame_from(
        from:{
            id:$idConsultation
        },
        to:{
            id:$idSchedule
        }
    ){
        from{id}, to{id}
    },
    UpdateConsultation(id:$idConsultation, canceled_schedule:true){
        id
    }
}