mutation($idConsultation:ID!, $year: int, $month: int, $day: int, $hour: int, $minute: int){
 UpdateConsultation(id:$idConsultation ,consultation_hour:{year: $year, month: $month, day: $day, hour: $hour, minute: $minute}){
              id
            }

}
