mutation($idCharge:ID!,$idCategory:ID!){

         AddChargeCategories(
                    from:{
                        id:$idCharge
                    },
                    to:{
                        id:$idCategory
                    }
                    ){
                    from{id},
                    to{id}
                    },
}