mutation {
    AddChargeWith_ProductTransaction(
        from:{
            id:$idCharge
        },
        to:{
            id:$idProductTransaction
        }
    ){
        from{id},
        to{id}
    }
}