mutation (
    $value: Float,
    $payment_methods: [String],
    $date: _Neo4jDateTimeInput,
    $description: String,
    $date_to_pay: _Neo4jDateTimeInput,
    $recurrent: Boolean,
    $type: String
     )
    {
    CreateCharge(
     value:$value,
     payment_methods:$payment_methods,
     date:{formatted: $date},
     description:$description,
     date_to_pay:{formatted: $date_to_pay},
     recorrent: $recurrent,
     type: $type
     ){
        id, value, payment_methods, date{formatted}
    }
}