query($type:String){
    Charge(filter:{type:$type}){
        date {formatted},value,date_to_pay{formatted},description,payment_methods,recorrent,id
        categories{
            name, id
        },
        unit:with_unit{
            name,id
        },
        colaborator{
            name,id
        }
    }
}