mutation CreateProduct(
    $specialty: String!,
    $type: String!,
    $price: Float!,
    $schedulable: Boolean!,
    ){
  CreateProduct(
    name: $specialty,
    type: $type,
    price: $price,
    schedulable: $schedulable,
  )
  {
    id,name,type,price
  }
}