mutation CreateProduct(
    $specialty: String!,
    $type: String!,
    $price: Float!,
    ){
  CreateProduct(
    name: $specialty,
    type: $type,
    price: $price,
  )
  {
    id,name,price
  }
}