query ($type: String!,$schedulable: Boolean) {
    Product (type: $type, schedulable: $schedulable){
        id,
        name,
        doctors{
            id,
            name,
            crm
        },
        clinics{
            id,
            name
        }
    }
}