query ($type: String!,$schedulable: Boolean) {
    Product (type: $type, schedulable: $schedulable){
        id,
        name,
        doctors{
            id,
            name,
            crm,
            cpf
        },
        price,
        final_price,
        clinics{
            id,
            name,
            cnpj,
            telephone,
             opening_hours,
             has_address{
                           cep, state, street, city, complement, neighboor, number
                         }
        }
    }
}