mutation($idTicket : ID! , $idCollaborator : ID!){
       AddColaboratorTickets_called_by_collaborator(
        from:{
          id: $idCollaborator
        },
        to:{
          id: $idTicket
        }
      ){
      from{id},
      to{id}
    },
}