mutation($idTicket : ID! , $idRoom : ID!){
       AddRoomRoom_has_tickets(
        from:{
          id:$idRoom
        },
        to:{
          id:$idTicket
        }
      ){
      from{id},
      to{id}
    },
}