mutation($idTicket : ID! , $idConsultation: ID!){
       AddTicketConsultation(
        from:{
          id: $idTicket
        },
        to:{
          id: $idConsultation
        }
      ){
      from{id},
      to{id}
    },
}