query{
  Colaborator(orderBy:[name_asc]){
    id,
    name,
    cpf,
    email,
    group,
    salary,
    permissions,
    birth_date,
    telephones,
    clinic:work_in{
      id,
      name,
      logo
    },
    tickets_called_by_collaborator{
      id,name,type,created_at{formatted},called_at{formatted},
    },
  }
}