mutation($idColaborator:ID!,$idClinic:ID!){
  RemoveColaboratorWork_in(
    from:{
        id:$idColaborator
    },
    to:{
        id:$idClinic
    }
  ){
      from{
          id
      },
      to{
          id
      }
  }
}