mutation($idClinic: ID!, $idAddress: ID!){
    AddClinicHas_address(
        from:{
            id:$idClinic
        },
        to:{
            id:$idAddress
        }
    ){
        from{id},
        to{id}
    },
}