query{
    Clinic(orderBy:[name_asc]){
        id,name,cnpj,telephone,logo,property,
         has_address{
            id,cep,state,street,city,complement,neighboor,number,geopoint{latitude,longitude}
         },
         charges{
            date {formatted},id,
            value,
            ProductTransaction: with_ProductTransaction{
               Product: with_product{
                   name
               }
            }
         }
    }
}