query($id:ID!){
    Clinic(id:$id){
         charges{
         _id,
            date {formatted},id,
            value,
            ProductTransaction: with_ProductTransaction{
               Product: with_product{
                   name, id
               },
               with_transactionPay{
               id, with_user{name}
               },
                with_transaction{
                id, with_user{name}
                }
            }
         }
    }
}
