mutation($idProduct: ID!, $idCostProduct: ID!){
    AddCostProductDoctorWith_product(
        from:{
            id:$idCostProduct
        },
        to:{
            id:$idProduct
        }
    ){
        from{id},
        to{id}
    },
}