mutation($idDoctor:ID!, $idClinic:ID!){
    AddClinicHas_doctor(
        from:{
            id:$idClinic
        },
        to:{
            id:$idDoctor
        }
    ){
        from{id},
        to{id}
    },
}