query {
    CostProductDoctor(orderBy:[cost_asc]){
       id,cost,payment_method
           with_doctor{
             id,name
           },
           with_product{
            id,name
           }
    }
}