query {
    Doctor(orderBy:[name_asc]){
        id,name,crm,cpf
        charges{
            date,
            value
            ProductTransaction: with_ProductTransaction{
                product: with_product{
                    name
                }
            }
        }
    }
}