query {
    Doctor(orderBy:[name_asc]){
        id,name,crm,cpf,
        charges{
           date {formatted},id,
           value,
           ProductTransaction: with_ProductTransaction{
              Consultation: with_consultation{
                  Product:has_product{
                      name
                  }
              }
           }
        }
    }
}