mutation($idProduct: ID!, $idCostProduct: ID!, $idDoctor: ID!){
    RemoveCostProductDoctorWith_product(
        from:{
            id:$idCostProduct
        },
        to:{
            id:$idProduct
        }
    ){
        from{id},
        to{id}
    },
    RemoveDoctorIs_specialist_of(
         from:{
                id:$idDoctor
         },
         to:{
                id:$idProduct
         }
        ){
            from{id},
            to{id}
    },
    RemoveCostProductDoctorWith_doctor(
          from:{
                id:$idCostProduct
            },
          to:{
                id:$idDoctor
            }
        ){
            from{id},
            to{id}
    },

}