mutation($idProductTransaction:ID!,$idConsultation:ID!){
  AddTransactionCancelled_by(
    from:{
      id:$idProductTransaction
    },
    to:{
      id:$idConsultation
    }
  ){
    from{id},to{id}
  },

  UpdateConsultation(id:$idConsultation,status:"Pago"){
    id
  }
}