mutation($idBudget:ID!,$idDoctor: ID!){
              AddTransactionWith_doctor(
                     from:{
                         id:$idBudget
                     },
                     to:{
                         id:$idDoctor
                     }
                 ){
                     from{id},
                     to{id}
                 }
}