mutation($idBudget:ID!,$idProduct:ID!, $idProductTransaction: ID!, $idUnit: ID!){
    AddProductTransactionWith_transaction(
        from:{
            id:$idProductTransaction
        },
        to:{
            id:$idBudget
        }
    ){
        from{id},
        to{id}
    },
    AddProductTransactionWith_product(
        from:{
            id:$idProductTransaction
        },
        to:{
            id:$idProduct
        }
        ){
        from{id},
        to{id}
        },
    AddTransactionWith_unit(
            from:{
                id:$idProductTransaction
            },
            to:{
                id:$idUnit
            }
            ){
            from{id},
            to{id}
            },

}