mutation($idOuttake:ID!, $idClinic: ID!){
    AddTransactionWith_clinic(
        from:{
            id:$idOuttake
        },
        to:{
            id:$idClinic
        }
    ){
        from{id},
        to{id}
    }

}