mutation AddTransactionWith_clinic($idClinic:ID!, $idTransaction: ID!){
    AddTransactionWith_clinic(
        from:{
            id:$idTransaction
        },
        to:{
            id:$idClinic
        }
    ){
        from{id},
        to{id}
    }
}