mutation($idBudget:ID!,$idColaborator:ID!, $idPatient: ID!, $idDoctor: ID!, $idUnit: ID!){
    AddColaboratorWith_transaction(
        from:{
            id:$idColaborator
        },
        to:{
            id:$idBudget
        }
    ){
        from{id},
        to{id}
    },
    AddTransactionWith_doctor(
        from:{
            id:$idBudget
        },
        to:{
            id:$idDoctor
        }
    ){
        from{id},
        to{id}
    },
    AddTransactionWith_user(
        from:{
            id:$idBudget
        },
        to:{
            id:$idPatient
        }
        ){
        from{id},
        to{id}
        },
        AddTransactionWith_unit(
         from:{
            id:$idProductTransaction
          },
         to:{
            id:$idUnit
             }
             ){
              from{id},
               to{id}
         },
}