mutation($idBudget:ID!,$idColaborator:ID!, $idPatient: ID!, $idDoctor: ID!){
    AddTransactionUserPayload(
        from:{
            id:$idBudget
        },
        to:{
            id:$idPatient
        }
    ){
        from{id},
        to{id}
    },
    AddTransactionColaboratorPayload(
        from:{
            id:$idBudget
        },
        to:{
            id:$idColaborator
        }
    ){
        from{id},
        to{id}
    },
    AddScheduleDoctors(
        from:{
            id:$idSchedule
        },
        to:{
            id:$idDoctor
        }
    ){
        from{id},
        to{id}
    }
}