mutation (
    $value: Float,
    $payment_methods: [String],
    $date: _Neo4jDateTimeInput,
    $description: String,
    $date_to_pay: _Neo4jDateTimeInput,
     )
    {
    CreateTransaction(
     value:$value,
     payment_methods:$payment_methods,
     date:$date,
     description:$description,
     date_to_pay:$date_to_pay,
     ){
        id, value, payment_methods, date{formatted}
    }
}