mutation (
    $id: ID!,
    $value: Float,
    $payment_methods: [String],
    $date: _Neo4jDateTimeInput,
    $description: String,
    $dat_pay: _Neo4jDateTimeInput,
     )
    {
    CreateTransaction(
        id: $id,
     value:$value,
     payment_methods:$payment_methods,
     date:$date,
     description:$description,
     date_to_pay:$dat_pay,
     ){
        id, value, payment_methods, date{formatted}
    }
}
