query($idPatient:ID!,$idProduct:ID!){
  ProductTransaction(filter:{with_transactionPay:{with_user:{id:$idPatient}},with_product:{id:$idProduct}, with_consultation:null}){
    id, _id,
    with_product{
      name
    }
  }
}