query GetTransactions($date_start: String, $unit_name: String, $date_final: String){
    Transaction(filter:{AND: [{date_gte: {formatted: $date_start}}, {date_lte: {formatted: $date_final}} {cancelled_by: null}, {with_unit_some: {name: $unit_name}}]}){
    date{
      formatted
    },
    id,
    discount,
    value,
    paid,
    payments,
    parcels,
    payment_methods,
    description,
    colaborator {
        name
    },
    categories{
    name
    },
    cancelled_by{
        id,
        name,
        cpf
        },
    produts: with_productTransaction_relations{
        price,
        averageCost,
        with_product{
            name,
            type, id
        },
        with_clinic{
            name, id
        }
        with_consultation{
                attended_by{
                    id
                }
        }
    }
    }
}
