mutation (
    $idTransaction: ID!,
    $idColaborator: ID!
    ) {
    AddTransactionCancelled_by(
        from:{
          id:$idTransaction
        },
        to:{
          id:$idColaborator
        }
      ){
        from{id},to{id}
      }
    }