query ($date_start: String, $date_end: String, $type: String!){
    Charge(filter: {
        type:$type,
        date_gte: {formatted: $date_start},
        date_lte: {formatted: $date_end},
        value_not: null,
        description_not: null
    }) {
        description,
        colaborator {
            name
            id
        },
        payment_methods,
        value,
        date_to_pay{formatted},
        date{formatted},
        id,
        with_unit {
            logo,
            name,
            id
        },
        categories {
            name
            id
        },
        balance
    }

}
