query($dateStart:String, $dateEnd:String){
      Transaction(filter:{AND: [{date_gte:{formatted:$dateStart}},{{date_lte:{formatted:$dateEnd}}]}){
        date{formatted}
        bundle{
        name, total
        }

    }
}