query ($date_start: String, $date_end: String) {
   Transaction (filter: {
    value_lt: 0,
    date_gte: {formatted: $date_start},
    date_lte: {formatted: $date_end}}) {
        value,
  	    description,
  	    date{formatted},
        categories{
            name
        },
        colaborator{
    	    name
        },
        payment_methods,
        id,
        with_unit{
            name,
            logo
        }
    },
}