query{
    Transaction(filter:{date_to_pay_not:{formatted:"2020-09-01T10"}}){
        date{formatted} ,value,date_to_pay{formatted},description,payment_methods,recorrent,id
        categories{
            name
        },
        unit:with_unit{
            name,id
        }

    }
}