query($email:String!){
  User(filter:{email:$email}){
    id,email,
    is_doctor{
      id,name,
      crm,
      cpf
    },
    is_patient{
      id,name,
      association_number,
      birth_date{
        formatted
      },
      cpf,
      name,
      sex,
      telephones
    },
    is_provider{
      id,name,
      cnpj,
      opening_hours,
      logo,
      property,
      telephone,
      has_address{
        id,
        cep,
        city,
        complement,
        number,
        neighboor,
        state,
        street,
        uf
      }
    },
    is_colaborator{
      id,
      name,
      cpf,
      email,
      group,
      salary,
      permissions,
      birth_date{formatted},
      clinic:work_in{
        id,
        name,
        logo
      }
    }
  }
}
