query{
	Schedule(orderBy:[id_desc]){
    id,
    interval,
    clinic:belongs_to{
      id,
      name
    },
    product:with_product{
      id,
      name,
      type,
      price,
      others:with_other{
        id,
        name
      }
    },
    doctor:exclusive_for{
      id,
      name
    },
    observations,
    days:for_day{
      id,
      day,
      expiration_date{
      	formatted
      },
      hour,
      vacancy
    },
    num_consultations,
    num_regress,
    consultations{
      id,
      date{formatted},
      type
    },
    canceled_periods{
      id,
      start_date{formatted},
      final_date{formatted}
    }
  }
}