query{
	Schedule(orderBy:[id_desc]){
    id,
    interval,
    clinic:belongs_to{
      id,
      name
    },
    product:with_product{
      id,
      name,
      type,
      price,
      others:with_other{
        id,
        name
      }
    },
    doctor:exclusive_for{
      id,
      name
    }
    days:for_day{
      id,
      day,
      expiration_date{
      	formatted
      },
      hour,
      vacancy
    },
    consultations{
      id
    },
    returns_consultations{
      id
    }
  }
}