mutation ($day: String!, $hour:String!, $vacancy:Int!) {
    CreateDay(day: $day,hour: $hour,vacancy: $vacancy){
        id,
        day,
        expiration_date{
            formatted
        },
        hour,
        vacancy
    },
}