mutation($idDay:ID!,$hour: String, $vacancy:Int, $expiration_date: _Neo4jDateInput){
        UpdateDay(id:$idDay, hour:$hour,vacancy:$vacancy,expiration_date:$expiration_date){
            id
        }
}