query($name: String!){
      Sector(name: $name){
        id,name, counter_reset, counter_normal, counter_priority, next_ticket_normal, next_ticket_priority
        sector_has_tickets{
            id,name,type,created_at{formatted},called_at{formatted},
          }
        has_rooms{
          name,id,previos_ticket,current_ticket
          room_has_tickets{
            id,name,type,created_at{formatted},called_at{formatted},
                                  patient{
                                    id,name
                                  }
          },
          doctor{
            id,name
          }
        }
   },
}