query($name: String!){
      Room(name: $name){
        name,id,previos_ticket,current_ticket, next_ticket_normal, next_ticket_priority
        room_has_tickets{
            id,name,type,created_at{formatted},called_at{formatted},
                            consultation{
                                id,
                                patient{
                                  id,name
                                }
                        }
        },
        doctor{
            id,name
        },
   },
}