query($name: String!){
      Sector(name: $name){
        id,name
        sector_has_tickets{
            id,name,type,created_at{formatted},called_at{formatted},
          }
        has_rooms{
          name,id
          room_has_tickets{
            id,name,type,created_at{formatted},called_at{formatted},
          }
        }
   },
}