query($name: String!){
      Sector(name: $name){
        id,name
        sector_has_tickets{
            id,name,type
          }
        has_rooms{
          name,id
          room_has_tickets{
            id,name,type
          }
        }
   },
}