query($name: String!){
      Room(name: $name){
        name,id,previos_ticket,current_ticket
        room_has_tickets{
            id,name,type,created_at{formatted},called_at{formatted}
        }
   },
}