mutation($idRoom: ID!, $idDoctor: ID!){
    RemoveRoomDoctor(
        from:{
            id:$idRoom
        },
        to:{
            id:$idDoctor
        }
    ){
        from{id},
        to{id}
    },
}