mutation CreatePatient(
    $name: String!,
    $birth_date: _Neo4jDateInput,
    $created_at: _Neo4jDateTimeInput,
    $cpf: String!,
    $sex: String,
    $association_number: Int,
    $telephones:[String]
    ){
  CreatePatient(
    name: $name,
    birth_date: $birth_date,
    cpf: $cpf,
    sex: $sex,
    association_number: $association_number,
    telephones:$telephones,
    created_at:$created_at
  )
  {
    id
  }
}