mutation CreatePatient(
    $name: String!,
    $email: String!
    $year: Int, $month: Int, $day: Int,
    $created_at: _Neo4jDateTimeInput,
    $cpf: String!,
    $sex: String,
    $association_number: Int,
    $telephones:[String]
    ){
  CreatePatient(
    name: $name,
    email: $email,
    birth_date: {year: $year, month: $month, day: $day},
    cpf: $cpf,
    sex: $sex,
    association_number: $association_number,
    telephones:$telephones,
    created_at:$created_at
  )
  {
    id
  }
}