query($id:ID!){
  Patient(filter:{id:$id}){
    id,
        name,
        cpf,
        birth_date,
        addresses{
            cep,
            city,
            complement,
            street,
            number,
            uf,
        }
        dependents{
        name,
        birth_date,
        dependentDegree,
        sex
        }
        consultations:with_consultation{
          id,
          type,
          status,
          date,
          payment_number
          clinic:of_clinic{
            id,name,logo
          },
          product:has_product{
            id,name,type,price
          },
          doctor:attended_by{
            id,name,crm
          },
          regress{
            id,
            type,
            status,
            date,
            payment_number
          },
         intakes{
                date,
               discount,
               value,
               id,
               payments,
               parcels,
               payment_methods,
               products: with_productTransaction_relations{
                  price,
                  with_product{
                     name,
                     type,
                   },
                  clinic: with_clinic{
                     id,
                     name,
                     logo,
                     cnpj,
                     telephone
                  }
                },
                with_unit{
                  id,
                  name,
                  logo,
                  cnpj,
                  telephone
                }
              },
          previous_consultation{
            id,
            type,
            status,
            date,
            payment_number
          },
        	patient{
            id,
            name,
            cpf
          },
          came_from{
            id
          }
        }
    }
  }