query($id:ID!){
  Patient(filter:{id:$id}){
   id,
       name,
       cpf,
       sex,
       telephones,
       association_number,
       birth_date,
       addresses{
           cep,
           city,
           complement,
           street,
           number,
           uf,
       },
       dependents{
       id,
       name,
       birth_date,
       dependentDegree,
       sex
       },
       consultations:with_consultation{
         id,
         type,
         status,
         date,
         payment_number
         clinic:of_clinic{
           id,name,logo
         },
         product:has_product{
           id,name,type,price
         },
         doctor:attended_by{
           id,name,crm
         },
         regress{
           id,
           type,
           status,
           date,
           payment_number
         },
         previous_consultation{
           id,
           type,
           status,
           date,
           payment_number
         },
       	patient{
           id,
           name,
           cpf,
           birth_date,
         },
         dependent{
           id,
           name,
           birth_date,
           dependentDegree,
           sex
         }
         came_from{
           id
         }
       }
     }
   }
