query($offset:Int!, $first:Int!){
  Patient(orderBy:name_asc, first:$first, offset:$offset){
    name,
    attedanceHistory{date{formatted}},
    email,
    telephones,
    created_at{formatted}
  }
}