query($start_date:String!, $final_date:String!){
  attendanceCount(start_date:$start_date,final_date:$final_date){
    date{formatted},times{hour,minute},count,patients_name,genres, patients_birth_date{formatted}
  },
  attendanceCountGeopoint(start_date:$start_date,final_date:$final_date){
    date{formatted},count,patients_name,geopoints{latitude,longitude}
  },
  createdPatientCount(start_date:$start_date,final_date:$final_date){
    date{formatted},count
  },
   attendanceCountGenres(final_date:$final_date){
    count,sex
  },
  attendanceCountAges(final_date:$final_date){
    count,age
  },
  attendanceCountHours(final_date:$final_date){
    count,hour
  },
  attendanceCountWeekDay(final_date:$final_date){
    count,weekday
  }
}