query($name:String){
  Patient(first:15, filter:{name_starts_with:$name}){
    id,
    name,
    cpf,
    sex,
    telephones,
    association_number,
    birth_date,
    addresses{
        cep,
        city,
        complement,
        street,
        number,
        uf,
    },
    dependents{
    id,
    name,
    birth_date,
    dependentDegree,
    sex
    },
    intakes{
       date,
       id,
      discount,
      value,
      payments,
      parcels,
      payment_methods,
      products: with_productTransaction_relations{
         price,
         with_product{
            name,
            type,
          },
         clinic: with_clinic{
            id,
            name,
            logo,
            cnpj,
            telephone,
            opening_hours,
            has_address{
                    neighboor,
                    city,
                    complement,
                    street,
                    number,
                    complement,
                    state,
                    cep
            }
         }
       },
       with_unit{
         id,
         name,
         logo,
         cnpj,
         telephone
       }
     },
    consultations:with_consultation{
      id,
      type,
      status,
      date,
      payment_number
      clinic:of_clinic{
        id,name,logo
      },
      product:has_product{
        id,name,type,price
      },
      doctor:attended_by{
        id,name,crm
      },
      regress{
        id,
        type,
        status,
        date,
        payment_number
      },
      previous_consultation{
        id,
        type,
        status,
        date,
        payment_number
      },
    	patient{
        id,
        name,
        cpf,
        birth_date,
      },
      dependent{
        id,
        name,
        birth_date,
        dependentDegree,
        sex
      }
      came_from{
        id
      }
    }
  }
}