query($name:String){
  Patient(first:15, filter:{name_starts_with:$name}){
    id,
    name,
    cpf,
    sex,
    telephones,
    association_number,
    birth_date{formatted},
    addresses{
        cep,
        city,
        complement,
        street,
        number,
        uf,
        geopoint{
          latitude,longitude
        }
    },
    dependents{
      id,
      name,
      birth_date{formatted},
      dependentDegree,
      sex
    },
    intakes{
      date {
        formatted
      },
      id,
      discount,
      value,
      payments,
      parcels,
      payment_methods,
       cancelled_by{
               id,
               name
       }
      products: with_productTransaction_relations{
         price,
         with_product{
            name,
            type,
          },
         id,
         clinic: with_clinic{
            id,
            name,
            logo,
            cnpj,
            telephone,
            opening_hours,
            has_address{
                    neighboor,
                    city,
                    complement,
                    street,
                    number,
                    complement,
                    state,
                    cep
            }
         }
       },
       with_unit{
         id,
         name,
         logo,
         cnpj,
         telephone
       }
     },
    consultations:with_consultation{
      id,
      type,
      status,
      date{formatted},
      payment_number,
      canceled_schedule,
      clinic:of_clinic{
        id,name,logo
      },
      product:has_product{
        id,name,type,price
      },
      doctor:attended_by{
        id,name,crm
      },
      regress{
        id,
        type,
        status,
        date{formatted},
        payment_number
      },
      previous_consultation{
        id,
        type,
        status,
        date{formatted},
        payment_number
      },
    	patient{
        id,
        name,
        cpf,
        birth_date{formatted},
      },
      dependent{
        id,
        name,
        birth_date{formatted},
        dependentDegree,
        sex
      }
      came_from{
        id
      }
    }
  }
}
