mutation (
    $idAddress: ID!,
    $city: String,
    $neighboor: String

    ){
    UpdateAddress(
        id: $idAddress
        city: $city,
        neighboor: $neighboor,
    )
    {
        id
    }
}