mutation UpdatePatient(
    $idPatient: ID!,
    $name: String!,
    $email: String!,
    $year: Int, $month: Int, $day: Int,
    $cpf: String!,
    $sex: String,
    $association_number: Int,
    $telephones:[String]
    ){
  UpdatePatient(
    id:$idPatient,
    email: $email,
    name: $name,
    birth_date: {year: $year, month: $month, day: $day},
    cpf: $cpf,
    sex: $sex,
    association_number: $association_number,
    telephones:$telephones
  )
  {
    id
  }
}