mutation CreateDependent(
    $name: String!,
    $year: Int, $month: Int, $day: Int,
    $dependentDegree: String!,
    $sex: String
    ){
  CreateDependent(
    name: $name,
    birth_date: {year: $year, month: $month, day: $day},
    dependentDegree: $dependentDegree,
    sex: $sex
  )
  {
    id
  }
}