mutation CreateDependent(
    $name: String!,
    $birth_date: _Neo4jDateInput,
    $dependentDegree: String!,
    $sex: String
    ){
  CreateDependent(
    name: $name,
    birth_date: $birth_date,
    dependentDegree: $dependentDegree,
    sex: $sex
  )
  {
    id
  }
}