mutation($idProductBudget:ID!, $idClinic:ID!){
    AddProductBudgetWith_clinic(
        from:{
            id:$idProductBudget
        },
        to:{
            id:$idClinic
        }
    ){
        from{id},
        to{id}
    },
}