mutation(
    $cep: String,
    $city: String,
    $complement: String,
    $neighboor: String,
    $number: String,
    $state: String,
    $street: String,
    ){
    CreateAddress(
    cep: $cep,
    city: $city,
    complement: $complement,
    neighboor: $neighboor,
    number: $number,
    state: $state,
    street: $street,
    )
    {id}
}