mutation (
    $id: ID!,
    $cep: String,
    $city: String,
    $complement: String,
    $geopoint: String,
    $neighboor: String,
    $number: String,
    $state: String,
    $street: String,
    ){
  UpdateAddress(
    id: $id,
    cep: $cep,
    city: $city,
    complement: $complement,
    geopoint: $geopoint,
    neighboor: $neighboor,
    number: $number,
    state: $state,
    street: $street,
  ){
    id, cep,city,geopoint,neighboor, number, state, street
  }
}